services:
  db:
    container_name: postgres_db
    image: postgres:18
    environment:
      POSTGRES_DB: article_feed
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    logging:
      driver: 'none'
    command:
      - postgres
      - -c
      - log_statement=none
      - -c
      - log_min_messages=panic
    volumes:
      - db-data:/var/lib/postgresql

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - ./backend/node_modules/@prisma/client:/app/node_modules/@prisma/client
      - /app/node_modules
    environment:
      PORT: 4000
      DATABASE_URL: postgres://postgres:postgres@db:5432/article_feed
      JWT_SECRET: your_jwt_secret
    depends_on:
      - db
    ports:
      - '4000:4000'

volumes:
  db-data:
